// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreaApp.Models;

#nullable disable

namespace StoreaApp.Migrations
{
    [DbContext(typeof(RepositoryContexts))]
    partial class RepositoryContextsModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StoreaApp.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Price = 3m,
                            ProductName = "kuku"
                        },
                        new
                        {
                            ProductId = 2,
                            Price = 4m,
                            ProductName = "huhuhu"
                        },
                        new
                        {
                            ProductId = 3,
                            Price = 3m,
                            ProductName = "dsfsdf"
                        },
                        new
                        {
                            ProductId = 4,
                            Price = 6m,
                            ProductName = "sdfdsfds"
                        },
                        new
                        {
                            ProductId = 5,
                            Price = 7m,
                            ProductName = "fghfghfg"
                        },
                        new
                        {
                            ProductId = 6,
                            Price = 8m,
                            ProductName = "fghfghgfh"
                        },
                        new
                        {
                            ProductId = 7,
                            Price = 4m,
                            ProductName = "erterteret"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
